# Generated by Django 5.0.7 on 2024-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0002_useremotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='question',
            field=models.TextField(),
        ),
    ]
