# Generated by Django 5.0.7 on 2024-10-08 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0003_alter_userquestionanswer_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionanswer',
            unique_together={('user', 'date_answered', 'question')},
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='source_type',
            field=models.CharField(choices=[('PREDEFINED', 'Predefined Question'), ('AI', 'AI-generated Question')], default='PREDEFINED', max_length=10),
        ),
    ]
