# Generated by Django 5.0.7 on 2024-10-08 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rememberTree', '0004_alter_userquestionanswer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userquestionanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userquestionanswer',
            name='predefined_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rememberTree.question'),
        ),
        migrations.AlterUniqueTogether(
            name='userquestionanswer',
            unique_together={('user', 'date_answered', 'predefined_question', 'question')},
        ),
    ]
