# Generated by Django 5.0.7 on 2024-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorialHall", "0004_remove_memorialhall_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorialhall",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
